using System;using System.Collections;using System.IO;using System.Linq;using System.Collections.Generic;using Newtonsoft.Json.Linq;using UnityEditor;using UnityEngine;
public static partial class MonsterWeakAttackPlayerLoopVerifier
{
 static float FixturePhysicalRadius(EnemyActor actor){var body=actor.CollisionRoot.GetComponentInChildren<CapsuleCollider>();return Mathf.Max(body.bounds.extents.x,body.bounds.extents.z);}
 static void StopFixtureAI(EnemyActor actor,bool disableCrowd=false){actor.AI.enabled=false;foreach(var b in actor.GetComponentsInChildren<MonoBehaviour>(true))if(b!=null&&(b.GetType().Name=="EnemySensor"||b.GetType().Name=="RunFallGuard"||(disableCrowd&&b.GetType().Name=="EnemyCrowdAgent")))b.enabled=false;actor.Animator.cullingMode=AnimatorCullingMode.AlwaysAnimate;actor.Movement.StopMovement();}
 static IEnumerator RunUndeadCrowdCases(JObject author)
 {
  Time.captureDeltaTime=1f/30;var definitions=AssetDatabase.FindAssets("t:EnemyThemeTable",new[]{"Assets/ProjectOverburst/Resources/Enemies/Themes/Tables"}).Select(g=>AssetDatabase.LoadAssetAtPath<EnemyThemeTable>(AssetDatabase.GUIDToAssetPath(g))).SelectMany(t=>t.Entries).Select(e=>e.definition).Where(d=>d!=null).Distinct().ToArray();
  var services=new GameObject("Owned crowd/death services");owned.Add(services);var inactive=new GameObject("Owned crowd/death inactive");inactive.transform.SetParent(services.transform,false);inactive.SetActive(false);var pool=services.AddComponent<EnemyPoolService>();pool.Configure(inactive.transform,0);var catalog=ScriptableObject.CreateInstance<EnemyCatalog>();owned.Add(catalog);catalog.Configure(definitions);var service=services.AddComponent<EnemySpawnService>();service.Configure(catalog,pool);
  var floor=GameObject.CreatePrimitive(PrimitiveType.Cube);owned.Add(floor);floor.name="Owned crowd/death ground";floor.transform.position=new Vector3(0,-.5f,0);floor.transform.localScale=new Vector3(100,1,100);
  bool verifyCrowd=(bool?)author["verifyCrowd"]??true;var deathIds=author["deathDefinitions"] is JArray ids?ids.Values<string>().ToArray():new[]{"DeathHarvest_Reaper","V3_darkKnight2","V3_SkeletonKnight_Small","V3_SkeletonKnight_Medium"};
  if(verifyCrowd){var radii=new JArray();bool radiusPass=definitions.Length==56;
  foreach(var d in definitions){var request=new EnemySpawnRequest(d,Vector3.zero,Quaternion.identity,null,null,null,null,1,1,95);if(!service.TrySpawn(request,out var actor))throw new Exception("Crowd roster spawn "+d.EnemyId);StopFixtureAI(actor);yield return null;var agent=actor.GetComponent<EnemyCrowdAgent>();float physical=FixturePhysicalRadius(actor),crowd=agent.BodyRadius,estimate=EnemyCrowdAgent.EstimateBodyRadius(actor.gameObject);bool valid=physical>.05f&&Mathf.Abs(crowd/physical-1.12f)<.001f&&Mathf.Abs(estimate-crowd)<.002f;radii.Add(new JObject{{"id",d.EnemyId},{"physical",physical},{"crowd",crowd},{"estimate",estimate},{"pass",valid}});radiusPass&=valid;service.Release(actor);yield return new WaitForFixedUpdate();}
  cases.Add(new JObject{{"scenario","live-56-individual-crowd-radii"},{"radii",radii},{"pass",radiusPass&&pool.LeasedCount==0&&pool.PendingReturnCount==0}});WriteResult("RUNNING");
  foreach(var pair in new[]{new[]{"V3_SkeletonKnight_Small","CavernMutants_Cephalonops"},new[]{"V3_SkeletonKnight_Medium","V3_Ghoul"},new[]{"DeathHarvest_Reaper","V3_darkKnight2"}}){
   var actors=new List<EnemyActor>();
   foreach(string id in pair){var d=definitions.Single(x=>x.EnemyId==id);var request=new EnemySpawnRequest(d,Vector3.zero,Quaternion.identity,null,null,null,null,1,1,97);if(!service.TrySpawn(request,out var actor))throw new Exception("Crowd pair spawn");StopFixtureAI(actor);actors.Add(actor);}yield return null;yield return new WaitForFixedUpdate();
   var first=actors[0];var second=actors[1];float physical=FixturePhysicalRadius(first)+FixturePhysicalRadius(second);float minimum=first.GetComponent<EnemyCrowdAgent>().BodyRadius+second.GetComponent<EnemyCrowdAgent>().BodyRadius;
   first.GetComponent<Rigidbody>().position=new Vector3(-physical*.48f,0,0);second.GetComponent<Rigidbody>().position=new Vector3(physical*.48f,0,0);Physics.SyncTransforms();var starting=actors.Select(a=>a.transform.position).ToArray();
   for(int i=0;i<100;i++){foreach(var a in actors)a.Movement.SetDestination(a.transform.position+Vector3.forward*30,0,EnemyLocomotionMode.Walk);yield return new WaitForFixedUpdate();yield return null;}
   float distance=Vector2.Distance(new Vector2(first.transform.position.x,first.transform.position.z),new Vector2(second.transform.position.x,second.transform.position.z));bool moving=actors.Select((a,i)=>Vector3.Distance(a.transform.position,starting[i])).All(d=>d>.4f);bool valid=moving&&distance>=minimum-.025f&&actors.All(a=>!a.Health.IsDead&&a.transform.localScale==Vector3.one);
   foreach(var a in actors){a.Movement.StopMovement();service.Release(a);}yield return null;yield return new WaitForFixedUpdate();cases.Add(new JObject{{"scenario","actual-crowd-parallel-pair"},{"ids",new JArray(pair)},{"physicalMinimum",physical},{"crowdMinimum",minimum},{"distance",distance},{"moving",moving},{"pass",valid&&pool.LeasedCount==0&&pool.PendingReturnCount==0}});WriteResult("RUNNING");
  }
  }
  floor.layer=30;var material=new Material(Shader.Find("Universal Render Pipeline/Lit"));owned.Add(material);material.SetColor("_BaseColor",new Color(.28f,.32f,.35f));floor.GetComponent<Renderer>().sharedMaterial=material;var sunObject=new GameObject("Owned death review light");owned.Add(sunObject);var sun=sunObject.AddComponent<Light>();sun.type=LightType.Directional;sun.intensity=2;sun.cullingMask=1<<30;sunObject.transform.rotation=Quaternion.Euler(45,-35,0);
  foreach(string id in deathIds){
   var d=definitions.Single(x=>x.EnemyId==id);var request=new EnemySpawnRequest(d,Vector3.zero,Quaternion.identity,null,null,null,null,1,1,99);if(!service.TrySpawn(request,out var actor))throw new Exception("Death spawn");StopFixtureAI(actor);foreach(var t in actor.GetComponentsInChildren<Transform>(true))t.gameObject.layer=30;yield return null;yield return new WaitForFixedUpdate();yield return null;
   var cameraObject=new GameObject("Owned death capture camera");owned.Add(cameraObject);var camera=cameraObject.AddComponent<Camera>();camera.enabled=false;camera.cullingMask=1<<30;camera.orthographic=true;camera.orthographicSize=id=="DeathHarvest_Reaper"?3.7f:id=="V3_darkKnight2"?2.2f:1.8f;camera.nearClipPlane=.01f;camera.farClipPlane=100;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.14f,.17f,.21f);var center=new Vector3(0,id=="DeathHarvest_Reaper"?1.7f:1,0);cameraObject.transform.position=center+new Vector3(3,1.4f,4)*camera.orthographicSize;cameraObject.transform.LookAt(center);
   string capture=Path.Combine(plan.directory,"death-frames",id);Directory.CreateDirectory(capture);float elapsed=0,nextCapture=0;int frame=0;bool seen=false,onlyDeath=true,grounded=true,nonLoop=false,held=false;float minBottom=float.PositiveInfinity;Vector3 terminal=Vector3.zero;bool terminalSet=false;float terminalDrift=0;var geometry=new JArray();var clip=d.AnimationProfile.Death;var startPosition=actor.transform.position;
   var controller=(UnityEditor.Animations.AnimatorController)d.AnimationProfile.RuntimeController;var state=controller.layers[0].stateMachine.states.Single(s=>s.state.name=="Death").state;float duration=clip.length/state.speed;nonLoop=!AnimationUtility.GetAnimationClipSettings(clip).loopTime;
   actor.Health.TakeDamage(new DamageInfo(actor.Health.MaxHp+10000,actor.transform.position,null,Vector3.back,0,false));float deadline=Time.time+clip.length+4;
   while(actor.IsLeased&&actor.gameObject.activeSelf&&Time.time<deadline){
    yield return null;elapsed+=Time.deltaTime;var info=actor.Animator.GetCurrentAnimatorStateInfo(0);seen|=info.IsName("Death");if(elapsed>.25f&&actor.IsLeased)onlyDeath&=info.IsName("Death");
    if(info.IsName("Death")&&elapsed>=nextCapture){var bounds=UpcomingMonsterThemeReviewSizing.GeometryBounds(actor.VisualRoot.gameObject);minBottom=Mathf.Min(minBottom,bounds.min.y);grounded&=bounds.min.y>=-.09f;geometry.Add(new JObject{{"time",elapsed},{"normalizedTime",info.normalizedTime},{"bottom",bounds.min.y}});if(elapsed>=duration+.15f){if(!terminalSet){terminal=bounds.center;terminalSet=true;}else terminalDrift=Mathf.Max(terminalDrift,Vector3.Distance(terminal,bounds.center));held=true;}CaptureDeathFrame(camera,Path.Combine(capture,frame.ToString("D4")+".png"));frame++;nextCapture=elapsed+.125f;}
   }
   bool released=!actor.IsLeased&&!actor.gameObject.activeSelf&&pool.PendingReturnCount==0;bool stationary=Vector3.Distance(startPosition,actor.transform.position)<.025f;UnityEngine.Object.Destroy(cameraObject);yield return null;yield return new WaitForFixedUpdate();if(!service.TrySpawn(request,out var reused))throw new Exception("Death reuse");StopFixtureAI(reused);yield return null;yield return new WaitForFixedUpdate();yield return null;bool reuse=!reused.Health.IsDead&&reused.Health.CurrentHp==reused.Health.MaxHp&&reused.CollisionRoot.GetComponentInChildren<CapsuleCollider>().enabled&&!reused.Movement.IsActionLocked;service.Release(reused);yield return null;yield return new WaitForFixedUpdate();
   cases.Add(new JObject{{"id",id},{"scenario","saved-death-ground-hold-fade-pool-reuse"},{"loopDisabled",nonLoop},{"seenDeath",seen},{"onlyDeath",onlyDeath},{"minimumGeometryY",minBottom},{"terminalHeld",held},{"terminalDrift",terminalDrift},{"stationary",stationary},{"released",released},{"reused",reuse},{"capturedFrames",frame},{"samples",geometry},{"pass",nonLoop&&seen&&onlyDeath&&grounded&&held&&terminalDrift<.025f&&stationary&&released&&reuse&&pool.LeasedCount==0&&pool.PendingReturnCount==0}});WriteResult("RUNNING");
  }
 }
 static void CaptureDeathFrame(Camera camera,string path){RenderTexture rt=null;Texture2D texture=null;var previous=RenderTexture.active;try{rt=new RenderTexture(480,480,24);rt.Create();camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;texture=new Texture2D(480,480,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,480,480),0,0);texture.Apply();File.WriteAllBytes(path,texture.EncodeToPNG());}finally{camera.targetTexture=null;RenderTexture.active=previous;if(rt!=null){rt.Release();UnityEngine.Object.Destroy(rt);}if(texture!=null)UnityEngine.Object.Destroy(texture);}}
}
