// Code generated by tools/generate-runtime-contracts; DO NOT EDIT.

namespace HeraAgent
{
    internal static class ProtocolContracts
    {
        internal const string RuntimeContractsSchemaVersion = "hera.runtime-contracts/1";
        internal const string ToolCatalogSchemaVersion = "hera.tool-catalog/1";
        internal const string ExecutionProtocolVersion = "hera.execution/1";

        internal const string FeatureApprovalV1 = "approval_v1";
        internal const string FeatureDomainEpochV1 = "domain_epoch_v1";
        internal const string FeatureExecutionProtocolV1 = "execution_protocol_v1";
        internal const string FeatureOperationLedgerV1 = "operation_ledger_v1";
        internal const string FeatureTaskBridgeV1 = "task_bridge_v1";
        internal const string FeatureToolCatalogV1 = "tool_catalog_v1";

        internal const int AssetConfigLockVersion = 1;
        internal const long AssetConfigLockStaleAfterMilliseconds = 120000L;
    }
}
